# Use a Node.js image
FROM node:22.13.1

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Run the React app with increased memory limit explicitly in CMD
CMD ["npm", "start"]
